name: workflow
on:
  - push
  - pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile

      - name: eslint
        run: yarn eslint

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile

      - name: build
        run: yarn build
        env:
          API_URL: ${{ secrets.API_URL }}

      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  deploys:
    runs-on: ubuntu-latest
    needs:
      - eslint
      - build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: download artifact
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
